### ISSUE TITLE
[Enhancement] Adjust permissions of newly created correspondents/tags

### ISSUE THREAD

**Issue by MorgothRB** [icereed/paperless-gpt#166]
I'm currently using my paperless ngx admin user to access the documents in paperless gpt. When paperless gpt creates a new correspondent only this admin user has permissions to see/use the new correspondent, for other users it's shown as "private". For manually created objects you can set default permissions in the user's profile, it looks like they are not used in this case.
It would be great if paperless gpt could just use the api user's default permissions.

**Comment by strandaster** [comment]
Is a workaround known to set the default permissions paperless wide? I'm observing the same issue.

**Comment by icereed** [comment]
The core of this is fixed in [v0.26.0 – "The Resilience Expansion"](https://github.com/icereed/paperless-gpt/releases/tag/v0.26.0): newly created correspondents no longer carry `"owner": null` (the field is omitted, so paperless-ngx assigns the API user), which means documents no longer show as "private" (thanks @sobrino89, #955). For finer-grained default permissions, feel free to open a focused follow-up.

**Comment by leopard151** [comment]
First, thank you because of this amazing app. Secondly, can we please change this? I have several members using paperless and I had created an username paperless-gpt just for this task. All the correspondent now assigned to paperless-gpt, so it shows up as private for every users in our group. Is there a way to change the owner to null so that everyone will see this corespondent?

Edit: for some reasons, the tags are always fine, everyone can see all the tags there even though tags have owner option too.

Edit 2: Actually the tags are also private, I set the CREATE_NEW_TAGS to false before, so it just used ones that I already created.

**Comment by sobrino89** [comment]
I will take a look at this and let you know

**Comment by sobrino89** [comment]
I opened #955, so let me correct the record: it did not fix this issue. It is what
causes the behaviour @leopard151 is seeing.

**What #955 actually changed.** Before it, paperless-gpt sent `"owner": null` when
creating a correspondent and paperless-ngx stored it as unowned. With `omitempty` the
field is dropped from the body, so paperless-ngx assigns the API user as the owner instead.

**Why that is backwards.** In paperless-ngx an unowned object is visible to everyone,
while an owned one is hidden from everyone except its owner. From
`documents/permissions.py`, byte-identical in 2.14.7, 2.20.15 and 3.1.0:

    objects_owned = manager.filter(owner=user)
    objects_unowned = manager.filter(owner__isnull=True)
    return objects_owned | objects_unowned | objects_with_perms

and:

    def has_perms_owner_aware(user, perms, obj):
        return obj.owner is None or obj.owner == user or checker.has_perm(perms, obj)

Checked against a live 3.1.0 instance: a non-superuser sees exactly the 3 unowned
correspondents and none of the 112 owned ones. So creating a dedicated `paperless-gpt`
service user, as @leopard151 did, is precisely the setup where this hurts most.

**My original justification was wrong.** I reported that ownerless correspondents made
their documents show up as "private". That symptom is real, but it is a frontend artifact,
not a permissions problem: the UI renders `"Private"` whenever a referenced ID is missing
from the correspondent list it has loaded, and a correspondent created while the page is
open is not in that list yet. I retested this end to end today on 3.1.0 with a build that
restores the pre-#955 serialisation. A newly created, unowned correspondent shows as
"Private" in the already-open tab and shows its real name after a reload. The API returns
it normally the whole time (`owner: null`, `user_can_change: true`). Nothing was ever
hidden. I should have hit refresh before writing that patch, and I am sorry for the
detour it caused.

**On tags** (@leopard151's second edit): `CreateTag` sends only `{"name": ...}` and never
an owner field, so paperless-ngx assigns the API user there too. That behaviour predates
#955 and is unaffected by it, but it has the same consequence.

**Suggested way forward.** Restoring the old serialisation is a one-character change, but
a plain revert is not obviously right either: an unowned object can be edited and deleted
by any user, which some multi-user setups will not want. So I would rather make it
explicit, for correspondents and tags alike:

    CREATED_OBJECT_OWNER = none        # "owner": null, visible to everyone (pre-v0.26.0)
                         | api_user    # current behaviour
                         | paperless_defaults

The third mode would read the API user's own defaults from `GET /api/ui_settings/`
(`settings.permissions` carries `default_owner` plus `default_view_users` /
`default_view_groups` and the edit equivalents) and map them onto `owner` and
`set_permissions`, which both the correspondent and tag serializers accept. That would
finally answer @MorgothRB's original request. Two caveats worth knowing before anyone
builds it: the endpoint requires the `view_uisettings` permission, so a bare service
account gets a 403 and the code has to degrade gracefully, and those defaults only exist
once the user has set them in the web UI, so for an account that has never logged in the
block is simply empty.

Happy to open a PR for whichever shape you prefer, @icereed. Given that the regression is
mine, I would suggest `none` as the default so the behaviour matches what it was before
v0.26.0, but that is your call since it changes behaviour for everyone who has upgraded.

**Comment by leopard151** [comment]
I'm genuinely impressed on how responsive you are. Thanks for your answer. Hopefully it will get implemented soon.
